#include "../tests/tests.h"

#include <cmath>
#include <fstream>
#include <sstream>

#include "../core/fileutils.h"
#include "../search/bayesposterior.h"

//Tests for the exact C++ port of the bmcts posterior math
//(search/bayesposterior.{h,cpp}).
//
//Golden values are generated by python/bayes_m2_golden_gen.py, which runs the
//REAL Python reference (bmcts.posterior) over a fixed battery of cases and
//writes both inputs and expected outputs to tests/data/bayesgolden.txt.
//This file hardcodes no battery: it reads inputs and expected outputs from
//the golden file, plus a handful of analytic invariant checks that need no
//goldens.

using namespace std;

static const string GOLDEN_FILE_BASENAME = "bayesgolden.txt";

static double looseTol(double actual, double expected) {
  //Relative 1e-9 or absolute 1e-12, whichever is looser.
  return std::max(1e-12, 1e-9 * std::max(std::fabs(actual), std::fabs(expected)));
}

static void checkClose(const string& what, double actual, double expected) {
  if(!(std::fabs(actual - expected) <= looseTol(actual, expected))) {
    ostringstream out;
    out << "Bayes golden mismatch: " << what
        << " actual=" << Global::doubleToString(actual)
        << " expected=" << Global::doubleToString(expected);
    Global::fatalError(out.str());
  }
}

static void checkCloseTol(const string& what, double actual, double expected, double tol) {
  if(!(std::fabs(actual - expected) <= tol)) {
    ostringstream out;
    out << "Bayes invariant failure: " << what
        << " actual=" << Global::doubleToString(actual)
        << " expected=" << Global::doubleToString(expected)
        << " tol=" << Global::doubleToString(tol);
    Global::fatalError(out.str());
  }
}

static void checkWeightInvariants(const string& what, const vector<double>& w) {
  double sum = 0.0;
  for(size_t i = 0; i < w.size(); i++) {
    if(!(w[i] >= 0.0))
      Global::fatalError("Bayes invariant failure: negative weight in " + what);
    sum += w[i];
  }
  if(std::fabs(sum - 1.0) > 1e-9)
    Global::fatalError("Bayes invariant failure: weights of " + what + " sum to " + Global::doubleToString(sum));
}

static double readDouble(istream& in, const string& what) {
  double x;
  if(!(in >> x))
    Global::fatalError("Bayes golden file parse error reading " + what);
  return x;
}

static int readInt(istream& in, const string& what) {
  int x;
  if(!(in >> x))
    Global::fatalError("Bayes golden file parse error reading " + what);
  return x;
}

static vector<double> readDoubles(istream& in, int k, const string& what) {
  vector<double> xs(k);
  for(int i = 0; i < k; i++)
    xs[i] = readDouble(in, what);
  return xs;
}

static int runGoldenTests(istream& in) {
  int numRecords = 0;
  string tok;
  while(in >> tok) {
    if(tok.size() > 0 && tok[0] == '#') {
      string restOfLine;
      getline(in, restOfLine);
      continue;
    }
    if(tok == "end")
      break;
    numRecords += 1;
    const string where = tok + " record " + Global::intToString(numRecords);

    if(tok == "stdmax") {
      int k = readInt(in, where);
      double expectedM = readDouble(in, where);
      double expectedV = readDouble(in, where);
      pair<double,double> mv = BayesPosterior::stdMaxMoments(k);
      checkClose(where + " m", mv.first, expectedM);
      checkClose(where + " v", mv.second, expectedV);
    }
    else if(tok == "clarkpair") {
      double m1 = readDouble(in, where);
      double v1 = readDouble(in, where);
      double m2 = readDouble(in, where);
      double v2 = readDouble(in, where);
      double expectedM = readDouble(in, where);
      double expectedV = readDouble(in, where);
      double m, v;
      BayesPosterior::clarkMaxPair(m1, v1, m2, v2, m, v);
      checkClose(where + " m", m, expectedM);
      checkClose(where + " v", v, expectedV);
      testAssert(v >= 0.0);
    }
    else if(tok == "clarkmaxw") {
      int k = readInt(in, where);
      vector<double> mus = readDoubles(in, k, where);
      vector<double> vars = readDoubles(in, k, where);
      double expectedM = readDouble(in, where);
      double expectedV = readDouble(in, where);
      vector<double> expectedW = readDoubles(in, k, where);
      double m, v;
      vector<double> w;
      BayesPosterior::clarkMaxAndWeights(mus, vars, m, v, w);
      checkClose(where + " m", m, expectedM);
      checkClose(where + " v", v, expectedV);
      for(int i = 0; i < k; i++)
        checkClose(where + " w[" + Global::intToString(i) + "]", w[i], expectedW[i]);
      checkWeightInvariants(where, w);
      testAssert(v >= 0.0);
    }
    else if(tok == "overlap") {
      int k = readInt(in, where);
      vector<double> mus = readDoubles(in, k, where);
      vector<double> vars = readDoubles(in, k, where);
      vector<double> expectedD = readDoubles(in, k, where);
      vector<double> d = BayesPosterior::overlapDensity(mus, vars);
      testAssert((int)d.size() == k);
      for(int i = 0; i < k; i++) {
        checkClose(where + " d[" + Global::intToString(i) + "]", d[i], expectedD[i]);
        testAssert(d[i] >= 0.0);
      }
    }
    else if(tok == "shrink") {
      int k = readInt(in, where);
      vector<double> evals = readDoubles(in, k, where);
      double vU = readDouble(in, where);
      double varS = readDouble(in, where);
      double sigmaD = readDouble(in, where);
      double anchorMu = readDouble(in, where);
      double anchorVar = readDouble(in, where);
      bool isMax = readInt(in, where) != 0;
      double cK = readDouble(in, where);
      double vK = readDouble(in, where);
      vector<double> expectedMus = readDoubles(in, k, where);
      double expectedVPriv = readDouble(in, where);
      double expectedVX = readDouble(in, where);
      double expectedKappa = readDouble(in, where);
      vector<double> mus;
      double vPriv, vX, kappa;
      BayesPosterior::shrinkSiblings(evals, vU, varS, sigmaD, anchorMu, anchorVar, isMax, cK, vK, mus, vPriv, vX, kappa);
      testAssert((int)mus.size() == k);
      for(int i = 0; i < k; i++)
        checkClose(where + " mu[" + Global::intToString(i) + "]", mus[i], expectedMus[i]);
      checkClose(where + " vPriv", vPriv, expectedVPriv);
      checkClose(where + " vX", vX, expectedVX);
      checkClose(where + " kappaAlpha", kappa, expectedKappa);
      testAssert(vPriv >= 0.0);
      testAssert(vX >= 0.0);
    }
    else if(tok == "nodepost") {
      int k = readInt(in, where);
      vector<double> mus = readDoubles(in, k, where);
      vector<double> vPrivs = readDoubles(in, k, where);
      vector<double> bs = readDoubles(in, k, where);
      double varS = readDouble(in, where);
      bool isMax = readInt(in, where) != 0;
      double expectedM = readDouble(in, where);
      double expectedVPriv = readDouble(in, where);
      double expectedB = readDouble(in, where);
      vector<double> expectedW = readDoubles(in, k, where);
      double m, vPriv, bOut;
      vector<double> w;
      BayesPosterior::nodePosteriorFromChildren(mus, vPrivs, bs, varS, isMax, m, vPriv, bOut, w);
      checkClose(where + " m", m, expectedM);
      checkClose(where + " vPriv", vPriv, expectedVPriv);
      checkClose(where + " bOut", bOut, expectedB);
      for(int i = 0; i < k; i++)
        checkClose(where + " w[" + Global::intToString(i) + "]", w[i], expectedW[i]);
      checkWeightInvariants(where, w);
      testAssert(vPriv >= 0.0);

      //Extra invariant on every golden case: a min node must be exactly the
      //negation of the corresponding max node with negated mus and bs.
      {
        vector<double> negMus(k);
        vector<double> negBs(k);
        for(int i = 0; i < k; i++) {
          negMus[i] = -mus[i];
          negBs[i] = -bs[i];
        }
        double m2, vPriv2, bOut2;
        vector<double> w2;
        BayesPosterior::nodePosteriorFromChildren(negMus, vPrivs, negBs, varS, !isMax, m2, vPriv2, bOut2, w2);
        checkCloseTol(where + " negation m", m2, -m, 1e-12);
        checkCloseTol(where + " negation vPriv", vPriv2, vPriv, 1e-12);
        checkCloseTol(where + " negation bOut", bOut2, -bOut, 1e-12);
        for(int i = 0; i < k; i++)
          checkCloseTol(where + " negation w[" + Global::intToString(i) + "]", w2[i], w[i], 1e-12);
      }
    }
    else if(tok == "extmom") {
      int k = readInt(in, where);
      vector<double> dMeans = readDoubles(in, k, where);
      double sigmaR = readDouble(in, where);
      bool isMax = readInt(in, where) != 0;
      double expectedED = readDouble(in, where);
      double expectedVD = readDouble(in, where);
      double expectedG = readDouble(in, where);
      double eD, vD, g;
      BayesPosterior::extremeMomentsGaussian(dMeans, sigmaR, isMax, eD, vD, g);
      checkClose(where + " eD", eD, expectedED);
      checkClose(where + " vD", vD, expectedVD);
      checkClose(where + " g", g, expectedG);
      testAssert(vD >= 0.0);
      testAssert(g >= 0.0);
    }
    else if(tok == "stein") {
      int k = readInt(in, where);
      int n = readInt(in, where);
      vector<double> evals = readDoubles(in, n, where);
      vector<int> evalIdx(n);
      for(int i = 0; i < n; i++)
        evalIdx[i] = readInt(in, where);
      double vU = readDouble(in, where);
      double varS = readDouble(in, where);
      double anchorMu = readDouble(in, where);
      double anchorVar = readDouble(in, where);
      double sigmaR = readDouble(in, where);
      double eD = readDouble(in, where);
      double vD = readDouble(in, where);
      double g = readDouble(in, where);
      bool hasDMeans = readInt(in, where) != 0;
      vector<double> dMeans;
      if(hasDMeans)
        dMeans = readDoubles(in, k, where);
      vector<double> expectedMus = readDoubles(in, k, where);
      vector<double> expectedVPriv = readDoubles(in, k, where);
      vector<double> expectedB = readDoubles(in, k, where);
      double expectedVX = readDouble(in, where);
      double expectedKappa = readDouble(in, where);
      double expectedCEE = readDouble(in, where);
      double expectedCUU = readDouble(in, where);
      double expectedCUE = readDouble(in, where);
      double expectedVE = readDouble(in, where);
      double expectedVU = readDouble(in, where);
      BayesPosterior::SteinShrink res = BayesPosterior::shrinkSiblingsStein(
        evals, evalIdx, k, vU, varS, anchorMu, anchorVar, sigmaR, eD, vD, g,
        hasDMeans ? &dMeans : NULL);
      testAssert((int)res.mus.size() == k);
      testAssert((int)res.vPriv.size() == k);
      testAssert((int)res.b.size() == k);
      for(int i = 0; i < k; i++) {
        checkClose(where + " mu[" + Global::intToString(i) + "]", res.mus[i], expectedMus[i]);
        checkClose(where + " vPriv[" + Global::intToString(i) + "]", res.vPriv[i], expectedVPriv[i]);
        checkClose(where + " b[" + Global::intToString(i) + "]", res.b[i], expectedB[i]);
        //Invariant: private variances are clamped nonnegative in every branch
        testAssert(res.vPriv[i] >= 0.0);
      }
      checkClose(where + " vX", res.vX, expectedVX);
      checkClose(where + " kappaAlpha", res.kappaAlpha, expectedKappa);
      checkClose(where + " cEE", res.cEE, expectedCEE);
      checkClose(where + " cUU", res.cUU, expectedCUU);
      checkClose(where + " cUE", res.cUE, expectedCUE);
      checkClose(where + " vE", res.vE, expectedVE);
      checkClose(where + " vU", res.vU, expectedVU);
      //Invariants: the factor variance is a covariance block clamped by the
      //branch conditions, and kappa is clipped to [0,1] at the end.
      testAssert(res.vX >= 0.0);
      testAssert(res.kappaAlpha >= 0.0 && res.kappaAlpha <= 1.0);
      //n = 0 invariant: with no evals the means are exactly the anchor-derived
      //prior means m_A + m_a = anchorMu - eD + dMeans[a] (no residual update).
      if(n == 0) {
        for(int i = 0; i < k; i++) {
          double priorMu = (anchorMu - eD) + (hasDMeans ? dMeans[i] : 0.0);
          checkCloseTol(where + " n=0 mus identity[" + Global::intToString(i) + "]",
                        res.mus[i], priorMu, 1e-15);
        }
      }
    }
    else {
      Global::fatalError("Bayes golden file: unknown record type '" + tok + "'");
    }
  }
  if(tok != "end")
    Global::fatalError("Bayes golden file: missing 'end' record");
  return numRecords;
}

static void runInvariantTests() {
  //stdMaxMoments basic properties
  {
    pair<double,double> mv = BayesPosterior::stdMaxMoments(1);
    testAssert(mv.first == 0.0);
    testAssert(mv.second == 1.0);
    double prevMean = 0.0;
    for(int k = 2; k <= 40; k += 3) {
      mv = BayesPosterior::stdMaxMoments(k);
      testAssert(mv.first > prevMean); //E[max of k] strictly increasing in k
      testAssert(mv.second > 0.0 && mv.second < 1.0);
      prevMean = mv.first;
    }
  }

  //Quadrature path with equal bs agrees with the homogeneous fast path to 1e-6
  {
    vector<double> mus;
    mus.push_back(0.2);
    mus.push_back(-0.1);
    mus.push_back(0.15);
    mus.push_back(0.05);
    vector<double> vPrivs;
    vPrivs.push_back(0.05);
    vPrivs.push_back(0.2);
    vPrivs.push_back(0.01);
    vPrivs.push_back(0.08);
    vector<double> bs(4, 0.7);
    double varS = 0.02;
    for(int isMaxInt = 0; isMaxInt <= 1; isMaxInt++) {
      bool isMax = isMaxInt != 0;
      double mFast, vFast, bFast;
      vector<double> wFast;
      BayesPosterior::nodePosteriorFromChildren(mus, vPrivs, bs, varS, isMax, mFast, vFast, bFast, wFast);
      double mQuad, vQuad, bQuad;
      vector<double> wQuad;
      const bool forceQuadrature = true;
      BayesPosterior::nodePosteriorFromChildren(mus, vPrivs, bs, varS, isMax, mQuad, vQuad, bQuad, wQuad, forceQuadrature);
      checkCloseTol("quad-vs-fast m", mQuad, mFast, 1e-6);
      checkCloseTol("quad-vs-fast vPriv", vQuad, vFast, 1e-6);
      checkCloseTol("quad-vs-fast bOut", bQuad, bFast, 1e-6);
      for(int i = 0; i < 4; i++)
        checkCloseTol("quad-vs-fast w", wQuad[i], wFast[i], 1e-6);
      checkWeightInvariants("quad-vs-fast", wQuad);
    }
  }

  //shrinkSiblings limits
  {
    vector<double> evals;
    evals.push_back(0.31);
    evals.push_back(-0.12);
    evals.push_back(0.05);
    evals.push_back(0.22);
    evals.push_back(-0.4);
    pair<double,double> ckvk = BayesPosterior::stdMaxMoments(5);
    for(int isMaxInt = 0; isMaxInt <= 1; isMaxInt++) {
      bool isMax = isMaxInt != 0;
      vector<double> mus;
      double vPriv, vX, kappa;
      //sigmaD huge: flat prior, mus ~= evals, kappaAlpha ~= 0
      BayesPosterior::shrinkSiblings(evals, 0.04, 0.01, 1e3, 0.1, 0.02, isMax, ckvk.first, ckvk.second, mus, vPriv, vX, kappa);
      for(int i = 0; i < 5; i++)
        checkCloseTol("shrink sigmaD=1e3 mu", mus[i], evals[i], 1e-3);
      checkCloseTol("shrink sigmaD=1e3 kappaAlpha", kappa, 0.0, 1e-4);
      testAssert(vPriv >= 0.0 && vX >= 0.0);
      //sigmaD tiny: every child collapses onto the common anchor estimate
      BayesPosterior::shrinkSiblings(evals, 0.04, 0.01, 1e-9, 0.1, 0.02, isMax, ckvk.first, ckvk.second, mus, vPriv, vX, kappa);
      double muMin = mus[0];
      double muMax = mus[0];
      for(int i = 1; i < 5; i++) {
        muMin = std::min(muMin, mus[i]);
        muMax = std::max(muMax, mus[i]);
      }
      checkCloseTol("shrink sigmaD=1e-9 spread", muMax - muMin, 0.0, 1e-12);
      testAssert(vPriv >= 0.0 && vX >= 0.0);
    }
  }
}

void Tests::runBayesTests() {
  cout << "Running bayes posterior tests" << endl;

  runInvariantTests();

  //Locate the golden file relative to cwd, like other tests/data loads
  //(works from the repo root, from cpp/, and from cpp/build/).
  vector<string> candidates;
  candidates.push_back("tests/data/" + GOLDEN_FILE_BASENAME);
  candidates.push_back("cpp/tests/data/" + GOLDEN_FILE_BASENAME);
  candidates.push_back("../tests/data/" + GOLDEN_FILE_BASENAME);
  string goldenPath;
  for(size_t i = 0; i < candidates.size(); i++) {
    if(FileUtils::exists(candidates[i])) {
      goldenPath = candidates[i];
      break;
    }
  }
  if(goldenPath.empty()) {
    cout << "Not being run out of git repo, skipping bayes golden tests" << endl;
    return;
  }

  ifstream in;
  FileUtils::open(in, goldenPath);
  int numRecords = runGoldenTests(in);
  cout << "Bayes posterior tests passed (" << numRecords << " golden records from " << goldenPath << ")" << endl;
}
