#include "../search/bayesposterior.h"

//Exact C++ port of bmcts src/bmcts/posterior.py. See bayesposterior.h.
//Every clamp, floor, and processing order below deliberately mirrors the
//Python reference; do not "clean up" numerics here without regenerating and
//re-passing the golden tests (tests/testbayes.cpp).

#include <algorithm>
#include <cassert>
#include <cmath>
#include <map>

namespace {
  const double SQRT2 = 1.4142135623730951;         //sqrt(2), matches Python math.sqrt(2.0)
  const double INV_SQRT_2PI = 0.3989422804014327;  //1/sqrt(2*pi)

  double normPdf(double x) {
    return INV_SQRT_2PI * std::exp(-0.5 * x * x);
  }
  double normCdf(double x) {
    return 0.5 * (1.0 + std::erf(x / SQRT2));
  }

  //Indices of mus in descending-mean order. Matches the Python reference's
  //processing order; stable, so exact ties keep ascending original index.
  std::vector<int> argsortDescending(const std::vector<double>& mus) {
    std::vector<int> order(mus.size());
    for(size_t i = 0; i < mus.size(); i++)
      order[i] = (int)i;
    std::stable_sort(order.begin(), order.end(), [&mus](int a, int b) { return mus[a] > mus[b]; });
    return order;
  }

  //Shared prefix/suffix Clark accumulators over the descending-mean order.
  //Fills ms, vs (sorted copies) and pre, suf (accumulated (m,v) pairs) exactly
  //like the Python p_argmax / overlap_density / clark_max_and_weights bodies.
  void buildClarkAccumulators(
    const std::vector<double>& mus, const std::vector<double>& vars,
    const std::vector<int>& order,
    std::vector<double>& ms, std::vector<double>& vs,
    std::vector<std::pair<double,double>>& pre,
    std::vector<std::pair<double,double>>& suf
  ) {
    const int k = (int)mus.size();
    ms.resize(k);
    vs.resize(k);
    for(int i = 0; i < k; i++) {
      ms[i] = mus[order[i]];
      vs[i] = vars[order[i]];
    }
    pre.resize(k);
    suf.resize(k);
    pre[0] = std::make_pair(ms[0], vs[0]);
    for(int i = 1; i < k; i++)
      BayesPosterior::clarkMaxPair(pre[i-1].first, pre[i-1].second, ms[i], vs[i], pre[i].first, pre[i].second);
    suf[k-1] = std::make_pair(ms[k-1], vs[k-1]);
    for(int i = k-2; i >= 0; i--)
      BayesPosterior::clarkMaxPair(ms[i], vs[i], suf[i+1].first, suf[i+1].second, suf[i].first, suf[i].second);
  }

  //Leave-one-out moments for arm j (in sorted order) from the accumulators.
  void leaveOneOutMoments(
    const std::vector<std::pair<double,double>>& pre,
    const std::vector<std::pair<double,double>>& suf,
    int j, int k, double& mo, double& vo
  ) {
    if(j == 0) {
      mo = suf[1].first;
      vo = suf[1].second;
    }
    else if(j == k-1) {
      mo = pre[k-2].first;
      vo = pre[k-2].second;
    }
    else {
      BayesPosterior::clarkMaxPair(pre[j-1].first, pre[j-1].second, suf[j+1].first, suf[j+1].second, mo, vo);
    }
  }

  //Probabilists' Gauss-Hermite nodes/weights for integrating over the shared
  //draw s ~ N(0, var_s); 9 points is plenty for the near-linear m(s).
  //Generated by numpy: x, w = numpy.polynomial.hermite_e.hermegauss(9); w /= w.sum()
  const int GH_N = 9;
  const double GH_X[GH_N] = {
    -4.512745863399783,
    -3.20542900285647,
    -2.07684797867783,
    -1.0232556637891326,
    0.0,
    1.0232556637891326,
    2.07684797867783,
    3.20542900285647,
    4.512745863399783,
  };
  const double GH_W[GH_N] = {
    2.23458440077466e-05,
    0.002789141321231769,
    0.049916406765217865,
    0.24409750289493945,
    0.4063492063492063,
    0.24409750289493945,
    0.049916406765217865,
    0.002789141321231769,
    2.23458440077466e-05,
  };
}

std::pair<double,double> BayesPosterior::stdMaxMoments(int k) {
  //Static cache: single-threaded use only, matching the Python module cache.
  static std::map<int, std::pair<double,double>> cache;
  assert(k >= 1);
  std::map<int, std::pair<double,double>>::iterator it = cache.find(k);
  if(it != cache.end())
    return it->second;
  if(k == 1) {
    cache[k] = std::make_pair(0.0, 1.0);
    return cache[k];
  }
  //x = np.linspace(-12.0, 12.0, 100001): x[i] = i*step + start, last point exact.
  const int n = 100001;
  const double start = -12.0;
  const double stop = 12.0;
  const double step = (stop - start) / (double)(n - 1);
  const double dx = (1.0 * step + start) - start; //x[1] - x[0], as Python computes it
  double sumX = 0.0;
  double sumXX = 0.0;
  for(int i = 0; i < n; i++) {
    double x = (i == n-1) ? stop : (double)i * step + start;
    double Phi = 0.5 * (1.0 + std::erf(x / SQRT2));
    double pdf = (double)k * normPdf(x) * std::pow(std::max(Phi, 1e-300), k - 1);
    sumX += x * pdf;
    sumXX += x * x * pdf;
  }
  double m = sumX * dx;
  double v = sumXX * dx - m * m;
  cache[k] = std::make_pair(m, v);
  return cache[k];
}

void BayesPosterior::clarkMaxPair(double m1, double v1, double m2, double v2, double& m, double& v) {
  double a2 = v1 + v2;
  if(a2 < 1e-18) {
    m = std::max(m1, m2);
    v = 0.0;
    return;
  }
  double a = std::sqrt(a2);
  double alpha = (m1 - m2) / a;
  double PhiA = 0.5 * (1.0 + std::erf(alpha / SQRT2));
  double phiA = INV_SQRT_2PI * std::exp(-0.5 * alpha * alpha);
  m = m1 * PhiA + m2 * (1.0 - PhiA) + a * phiA;
  double ex2 = (m1 * m1 + v1) * PhiA + (m2 * m2 + v2) * (1.0 - PhiA) + (m1 + m2) * a * phiA;
  v = std::max(ex2 - m * m, 1e-12);
}

void BayesPosterior::clarkMaxAndWeights(
  const std::vector<double>& mus, const std::vector<double>& vars,
  double& mOut, double& vOut, std::vector<double>& wOut
) {
  const int k = (int)mus.size();
  assert(k >= 1);
  assert((int)vars.size() == k);
  if(k == 1) {
    mOut = mus[0];
    vOut = vars[0];
    wOut.assign(1, 1.0);
    return;
  }
  std::vector<int> order = argsortDescending(mus);
  std::vector<double> ms;
  std::vector<double> vs;
  std::vector<std::pair<double,double>> pre;
  std::vector<std::pair<double,double>> suf;
  buildClarkAccumulators(mus, vars, order, ms, vs, pre, suf);

  std::vector<double> ws(k);
  for(int j = 0; j < k; j++) {
    double mo, vo;
    leaveOneOutMoments(pre, suf, j, k, mo, vo);
    double z = (ms[j] - mo) / std::sqrt(std::max(vs[j] + vo, 1e-18));
    ws[j] = normCdf(z);
  }
  wOut.assign(k, 0.0);
  double sum = 0.0;
  for(int j = 0; j < k; j++) {
    wOut[order[j]] = ws[j];
    sum += ws[j];
  }
  if(sum > 0.0) {
    for(int i = 0; i < k; i++)
      wOut[i] /= sum;
  }
  else {
    for(int i = 0; i < k; i++)
      wOut[i] = 1.0 / (double)k;
  }
  mOut = pre[k-1].first;
  vOut = pre[k-1].second;
}

std::vector<double> BayesPosterior::overlapDensity(
  const std::vector<double>& mus, const std::vector<double>& vars
) {
  const int k = (int)mus.size();
  assert(k >= 1);
  assert((int)vars.size() == k);
  if(k == 1)
    return std::vector<double>(1, 0.0);
  std::vector<int> order = argsortDescending(mus);
  std::vector<double> ms;
  std::vector<double> vs;
  std::vector<std::pair<double,double>> pre;
  std::vector<std::pair<double,double>> suf;
  buildClarkAccumulators(mus, vars, order, ms, vs, pre, suf);

  std::vector<double> out(k);
  for(int j = 0; j < k; j++) {
    double mo, vo;
    leaveOneOutMoments(pre, suf, j, k, mo, vo);
    double s = std::sqrt(std::max(vs[j] + vo, 1e-18));
    double z = (ms[j] - mo) / s;
    out[order[j]] = 0.5 * INV_SQRT_2PI * std::exp(-0.5 * z * z) / s;
  }
  return out;
}

void BayesPosterior::shrinkSiblings(
  const std::vector<double>& evals,
  double vU, double varS, double sigmaD,
  double anchorMu, double anchorVar,
  bool isMaxNode, double cK, double vK,
  std::vector<double>& musOut, double& vPrivOut, double& vXOut, double& kappaAlphaOut
) {
  const int k = (int)evals.size();
  assert(k >= 1);
  double sign = isMaxNode ? 1.0 : -1.0;
  double mA = anchorMu - sign * cK * sigmaD;
  double VA = anchorVar + vK * sigmaD * sigmaD;
  double vN = sigmaD * sigmaD + vU;
  if(vN <= 1e-18) {
    //exact evals of identical values: nothing to shrink
    musOut = evals;
    vPrivOut = 0.0;
    vXOut = 0.0;
    kappaAlphaOut = 0.0;
    return;
  }
  double eBar = 0.0;
  for(int i = 0; i < k; i++)
    eBar += evals[i];
  eBar /= (double)k;
  double pA = 1.0 / std::max(VA + varS, 1e-18);
  double pE = (double)k / vN;
  double Vt = 1.0 / (pA + pE);
  double mT = Vt * (pA * mA + pE * eBar);
  double omega = pA * Vt;
  double gamma = VA / std::max(VA + varS, 1e-18);
  double w = sigmaD * sigmaD / vN;
  double cHat = mA + gamma * (mT - mA);
  musOut.resize(k);
  for(int i = 0; i < k; i++)
    musOut[i] = cHat + w * (evals[i] - mT);
  vPrivOut = w * vU;
  double kappaAlpha = (1.0 - gamma) + (gamma - w) * omega;
  double gw = gamma - w;
  double VX =
    kappaAlpha * kappaAlpha * VA
    + (gamma - gw * omega) * (gamma - gw * omega) * varS
    + gw * gw * (1.0 - omega) * (1.0 - omega) * vN / (double)k;
  vXOut = std::max(VX, 0.0);
  kappaAlphaOut = kappaAlpha;
}

void BayesPosterior::nodePosteriorFromChildren(
  const std::vector<double>& childMus,
  const std::vector<double>& childVPrivs,
  const std::vector<double>& childBs,
  double varS, bool isMaxNode,
  double& mOut, double& vPrivOut, double& bOut, std::vector<double>& wOut,
  bool forceQuadrature
) {
  const int k = (int)childMus.size();
  assert(k >= 1);
  assert((int)childVPrivs.size() == k);
  assert((int)childBs.size() == k);
  std::vector<double> mus = childMus;
  std::vector<double> bs = childBs;
  if(!isMaxNode) {
    for(int i = 0; i < k; i++) {
      mus[i] = -mus[i];
      bs[i] = -bs[i];
    }
  }
  double bMin = bs[0];
  double bMax = bs[0];
  for(int i = 1; i < k; i++) {
    bMin = std::min(bMin, bs[i]);
    bMax = std::max(bMax, bs[i]);
  }
  bool homogeneous = (varS <= 0.0 || (bMax - bMin) < 1e-12);
  if(homogeneous && !(forceQuadrature && varS > 0.0)) {
    //homogeneous coefficients: max_a(mu_a + b*s + eta_a) = b*s + max_a(mu_a + eta_a)
    //exactly, so the shared part passes through additively — no quadrature
    double m, v;
    clarkMaxAndWeights(mus, childVPrivs, m, v, wOut);
    double b = (varS > 0.0) ? bs[0] : 0.0;
    if(!isMaxNode) {
      m = -m;
      b = -b;
    }
    mOut = m;
    vPrivOut = v;
    bOut = b;
    return;
  }
  double sd = std::sqrt(varS);
  double mAcc = 0.0;
  double ex2Acc = 0.0;
  double covAcc = 0.0;
  wOut.assign(k, 0.0);
  std::vector<double> shifted(k);
  std::vector<double> wS;
  for(int q = 0; q < GH_N; q++) {
    double s = GH_X[q] * sd;
    for(int i = 0; i < k; i++)
      shifted[i] = mus[i] + bs[i] * s;
    double mS, vS;
    clarkMaxAndWeights(shifted, childVPrivs, mS, vS, wS);
    for(int i = 0; i < k; i++)
      wOut[i] += GH_W[q] * wS[i];
    mAcc += GH_W[q] * mS;
    ex2Acc += GH_W[q] * (vS + mS * mS);
    covAcc += GH_W[q] * mS * s;
  }
  double vTotal = std::max(ex2Acc - mAcc * mAcc, 1e-12);
  double b = covAcc / varS;
  double vPriv = std::max(vTotal - b * b * varS, 1e-12);
  double m = mAcc;
  if(!isMaxNode) {
    m = -m;
    b = -b;
  }
  mOut = m;
  vPrivOut = vPriv;
  bOut = b;
}
