#!/usr/bin/env python3
"""Golden-value generator for the C++ port of the bmcts posterior math.

Runs the REAL Python reference implementation (bmcts.posterior) over a fixed
battery of cases and writes cpp/tests/data/bayesgolden.txt containing BOTH the
inputs and the expected outputs, so the C++ test (tests/testbayes.cpp) reads
the whole battery from the file and hardcodes nothing.

Run with:
    cd ~/Code/bmcts && uv run python ~/Code/KataGo/python/bayes_m2_golden_gen.py

File format: '#' lines are comments; every record is one whitespace-separated
line. Numbers are printed with repr() (shortest round-trip). Records:

    stdmax   k  |  m v
    clarkpair m1 v1 m2 v2  |  m v
    clarkmaxw k mus*k vars*k  |  m v w*k
    overlap   k mus*k vars*k  |  d*k
    shrink    k evals*k vU varS sigmaD anchorMu anchorVar isMax cK vK
              |  mus*k vPriv vX kappaAlpha
    nodepost  k mus*k vprivs*k bs*k varS isMax  |  m vPriv bOut w*k
    end

(the '|' is notional; records are flat token sequences, inputs then outputs)
"""
import os
import sys

sys.path.insert(0, os.path.expanduser("~/Code/bmcts/src"))

import numpy as np
from bmcts import posterior as P


def fmt(x):
    return repr(float(x))


def fmts(xs):
    return " ".join(fmt(x) for x in xs)


lines = []
lines.append("# Golden values for cpp/search/bayesposterior.{h,cpp}")
lines.append("# Generated by python/bayes_m2_golden_gen.py from bmcts.posterior")
lines.append("# (the Python reference implementation). Do not edit by hand;")
lines.append("# regenerate with: cd ~/Code/bmcts && uv run python ~/Code/KataGo/python/bayes_m2_golden_gen.py")


# ---------------------------------------------------------------- stdmax
for k in (1, 2, 3, 5, 8, 20, 40):
    m, v = P.std_max_moments(k)
    lines.append(f"stdmax {k} {fmt(m)} {fmt(v)}")


# ---------------------------------------------------------------- clarkpair
CLARKPAIR_CASES = [
    (0.1, 0.05, -0.2, 0.1),
    (0.5, 0.03, 0.5000000001, 0.07),       # near-tied means
    (2.0, 0.01, -2.0, 0.04),               # extreme gap ~ 20+ sd
    (0.1, 1e-10, 0.100001, 1e-10),         # tiny variances
    (0.3, 0.0, -0.3, 0.0),                 # a2 < 1e-18 branch
    (-0.7, 4e-19, -0.700000001, 4e-19),    # a2 < 1e-18 branch, near-tie
    (0.0, 1.0, 0.0000000001, 1.0),
    (-1.5, 0.5, 1.5, 0.25),
]
for m1, v1, m2, v2 in CLARKPAIR_CASES:
    m, v = P.clark_max_pair(m1, v1, m2, v2)
    lines.append(f"clarkpair {fmts([m1, v1, m2, v2])} {fmt(m)} {fmt(v)}")


# ------------------------------------------------- clarkmaxw + overlap
# Fixed literal (mus, vars) cases; the seeded-rng cases below are fixed too
# (fixed seed, values written into the file).
rng = np.random.default_rng(20260712)

MV_CASES = [
    # k = 1
    ([0.3], [0.2]),
    # k = 2 basic
    ([0.1, -0.2], [0.05, 0.1]),
    # k = 2 near-tied means
    ([0.5, 0.5000000001], [0.03, 0.07]),
    # k = 2 extreme mean gap (|mu diff| ~ 20*sd and beyond)
    ([2.0, -2.0], [0.01, 0.04]),
    # k = 2 tiny variances
    ([0.1, 0.100001], [1e-10, 1e-10]),
    # k = 3 mixed
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01]),
    # k = 3 near-tied triple
    ([0.0, 1e-10, -1e-10], [0.1, 0.1, 0.1]),
    # k = 5 mixed signs and scales
    ([0.3, -0.5, 0.12, 0.11, -0.02], [0.04, 0.09, 0.01, 0.16, 0.02]),
    # k = 5 with a tiny variance in the mix
    ([0.25, 0.24, -0.3, 0.1, 0.0], [1e-10, 0.05, 0.02, 0.03, 0.01]),
    # k = 8 seeded
    (list(rng.normal(0.0, 0.5, 8)), list(rng.uniform(0.005, 0.2, 8))),
    # k = 20 seeded
    (list(rng.normal(0.0, 0.3, 20)), list(rng.uniform(0.002, 0.15, 20))),
    # k = 20 extreme gaps
    (list(np.linspace(-5.0, 5.0, 20)), list(rng.uniform(0.01, 0.05, 20))),
]

for mus, vars_ in MV_CASES:
    mus_a = np.asarray(mus, dtype=float)
    vars_a = np.asarray(vars_, dtype=float)
    k = len(mus)
    m, v, w = P.clark_max_and_weights(mus_a, vars_a)
    lines.append(f"clarkmaxw {k} {fmts(mus)} {fmts(vars_)} {fmt(m)} {fmt(v)} {fmts(w)}")
    d = P.overlap_density(mus_a, vars_a)
    lines.append(f"overlap {k} {fmts(mus)} {fmts(vars_)} {fmts(d)}")


# ---------------------------------------------------------------- shrink
SHRINK_EVALS = {
    2: [0.18, -0.07],
    5: [0.31, -0.12, 0.05, 0.22, -0.4],
    8: list(rng.normal(0.05, 0.3, 8)),
}
V_U = 0.04
ANCHOR_MU = 0.1
ANCHOR_VAR = 0.02

shrink_records = []
for sigma_d in (1e-6, 0.05, 0.3, 5.0):
    for var_s in (0.0, 0.01):
        for is_max in (True, False):
            for k in (2, 5, 8):
                c_k, v_k = P.std_max_moments(k)
                shrink_records.append(
                    (SHRINK_EVALS[k], V_U, var_s, sigma_d, ANCHOR_MU, ANCHOR_VAR, is_max, c_k, v_k))
# v_n <= 1e-18 early-return branch: sigma_d = 0, v_u = 0
shrink_records.append(([0.2, 0.2, 0.2], 0.0, 0.01, 0.0, 0.1, 0.02, True, *P.std_max_moments(3)))

for evals, v_u, var_s, sigma_d, a_mu, a_var, is_max, c_k, v_k in shrink_records:
    k = len(evals)
    mus, v_priv, v_x, kappa = P.shrink_siblings(
        np.asarray(evals, dtype=float), v_u, var_s, sigma_d, a_mu, a_var, is_max,
        d_moments=(c_k, v_k))
    lines.append(
        f"shrink {k} {fmts(evals)} {fmt(v_u)} {fmt(var_s)} {fmt(sigma_d)} "
        f"{fmt(a_mu)} {fmt(a_var)} {1 if is_max else 0} {fmt(c_k)} {fmt(v_k)} "
        f"{fmts(mus)} {fmt(v_priv)} {fmt(v_x)} {fmt(kappa)}")


# ---------------------------------------------------------------- nodepost
NODEPOST_CASES = [
    # (mus, v_privs, bs, var_s, is_max)
    # k = 1
    ([0.2], [0.05], [1.0], 0.01, True),
    # heterogeneous bs incl mixed signs (quadrature path), both node types
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, -0.5, 0.3], 0.01, True),
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, -0.5, 0.3], 0.01, False),
    # homogeneous bs (fast path with b_out = bs[0])
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, 1.0, 1.0], 0.01, True),
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [0.7, 0.7, 0.7], 0.01, False),
    # var_s = 0 (fast path with b_out = 0, heterogeneous bs irrelevant)
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, -0.5, 0.3], 0.0, True),
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, -0.5, 0.3], 0.0, False),
    # k = 2 near-tied means, heterogeneous bs
    ([0.5, 0.5000000001], [0.03, 0.07], [0.9, 0.2], 0.02, True),
    # k = 2 extreme mean gap
    ([2.0, -2.0], [0.01, 0.04], [1.0, -1.0], 0.02, True),
    # k = 2 tiny variances
    ([0.1, 0.100001], [1e-10, 1e-10], [0.5, 1.5], 0.005, True),
    # k = 5, mixed-sign bs, both node types
    ([0.3, -0.5, 0.12, 0.11, -0.02], [0.04, 0.09, 0.01, 0.16, 0.02],
     [1.2, -0.3, 0.0, 0.8, -1.0], 0.04, True),
    ([0.3, -0.5, 0.12, 0.11, -0.02], [0.04, 0.09, 0.01, 0.16, 0.02],
     [1.2, -0.3, 0.0, 0.8, -1.0], 0.04, False),
    # k = 8 seeded, heterogeneous bs
    (list(rng.normal(0.0, 0.4, 8)), list(rng.uniform(0.005, 0.15, 8)),
     list(rng.normal(0.5, 0.6, 8)), 0.01, True),
    # k = 20 seeded, heterogeneous bs, min node
    (list(rng.normal(0.0, 0.3, 20)), list(rng.uniform(0.002, 0.1, 20)),
     list(rng.normal(0.0, 1.0, 20)), 0.02, False),
    # k = 20 homogeneous bs (ptp < 1e-12 threshold check: exactly equal)
    (list(rng.normal(0.0, 0.3, 20)), list(rng.uniform(0.002, 0.1, 20)),
     [0.6] * 20, 0.02, True),
]

for mus, v_privs, bs, var_s, is_max in NODEPOST_CASES:
    k = len(mus)
    m, v_priv, b_out, w = P.node_posterior_from_children(
        np.asarray(mus, dtype=float), np.asarray(v_privs, dtype=float),
        np.asarray(bs, dtype=float), var_s, is_max)
    lines.append(
        f"nodepost {k} {fmts(mus)} {fmts(v_privs)} {fmts(bs)} {fmt(var_s)} "
        f"{1 if is_max else 0} {fmt(m)} {fmt(v_priv)} {fmt(b_out)} {fmts(w)}")

lines.append("end")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "..", "cpp", "tests", "data", "bayesgolden.txt")
out_path = os.path.normpath(out_path)
with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"Wrote {len(lines)} lines to {out_path}")
