#!/usr/bin/env python3
"""Golden-value generator for the C++ port of the bmcts posterior math.

Runs the REAL Python reference implementation (bmcts.posterior) over a fixed
battery of cases and writes cpp/tests/data/bayesgolden.txt containing BOTH the
inputs and the expected outputs, so the C++ test (tests/testbayes.cpp) reads
the whole battery from the file and hardcodes nothing.

Run with:
    cd ~/Code/bmcts && uv run python ~/Code/KataGo/python/bayes_m2_golden_gen.py

File format: '#' lines are comments; every record is one whitespace-separated
line. Numbers are printed with repr() (shortest round-trip). Records:

    stdmax   k  |  m v
    clarkpair m1 v1 m2 v2  |  m v
    clarkmaxw k mus*k vars*k  |  m v w*k
    overlap   k mus*k vars*k  |  d*k
    shrink    k evals*k vU varS sigmaD anchorMu anchorVar isMax cK vK
              |  mus*k vPriv vX kappaAlpha
    nodepost  k mus*k vprivs*k bs*k varS isMax  |  m vPriv bOut w*k
    extmom    k dmeans*k sigmaR isMax  |  eD vD g
    stein     k n evals*n idx*n vU varS anchorMu anchorVar sigmaR
              eD vD g hasDMeans dmeans*k(only if hasDMeans)
              |  mus*k vpriv*k b*k vX kappaAlpha cEE cUU cUE vE vU
    end

(the '|' is notional; records are flat token sequences, inputs then outputs)
"""
import os
import sys

sys.path.insert(0, os.path.expanduser("~/Code/bmcts/src"))

import numpy as np
from bmcts import posterior as P


def fmt(x):
    return repr(float(x))


def fmts(xs):
    return " ".join(fmt(x) for x in xs)


lines = []
lines.append("# Golden values for cpp/search/bayesposterior.{h,cpp}")
lines.append("# Generated by python/bayes_m2_golden_gen.py from bmcts.posterior")
lines.append("# (the Python reference implementation). Do not edit by hand;")
lines.append("# regenerate with: cd ~/Code/bmcts && uv run python ~/Code/KataGo/python/bayes_m2_golden_gen.py")


# ---------------------------------------------------------------- stdmax
for k in (1, 2, 3, 5, 8, 20, 40):
    m, v = P.std_max_moments(k)
    lines.append(f"stdmax {k} {fmt(m)} {fmt(v)}")


# ---------------------------------------------------------------- clarkpair
CLARKPAIR_CASES = [
    (0.1, 0.05, -0.2, 0.1),
    (0.5, 0.03, 0.5000000001, 0.07),       # near-tied means
    (2.0, 0.01, -2.0, 0.04),               # extreme gap ~ 20+ sd
    (0.1, 1e-10, 0.100001, 1e-10),         # tiny variances
    (0.3, 0.0, -0.3, 0.0),                 # a2 < 1e-18 branch
    (-0.7, 4e-19, -0.700000001, 4e-19),    # a2 < 1e-18 branch, near-tie
    (0.0, 1.0, 0.0000000001, 1.0),
    (-1.5, 0.5, 1.5, 0.25),
]
for m1, v1, m2, v2 in CLARKPAIR_CASES:
    m, v = P.clark_max_pair(m1, v1, m2, v2)
    lines.append(f"clarkpair {fmts([m1, v1, m2, v2])} {fmt(m)} {fmt(v)}")


# ------------------------------------------------- clarkmaxw + overlap
# Fixed literal (mus, vars) cases; the seeded-rng cases below are fixed too
# (fixed seed, values written into the file).
rng = np.random.default_rng(20260712)

MV_CASES = [
    # k = 1
    ([0.3], [0.2]),
    # k = 2 basic
    ([0.1, -0.2], [0.05, 0.1]),
    # k = 2 near-tied means
    ([0.5, 0.5000000001], [0.03, 0.07]),
    # k = 2 extreme mean gap (|mu diff| ~ 20*sd and beyond)
    ([2.0, -2.0], [0.01, 0.04]),
    # k = 2 tiny variances
    ([0.1, 0.100001], [1e-10, 1e-10]),
    # k = 3 mixed
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01]),
    # k = 3 near-tied triple
    ([0.0, 1e-10, -1e-10], [0.1, 0.1, 0.1]),
    # k = 5 mixed signs and scales
    ([0.3, -0.5, 0.12, 0.11, -0.02], [0.04, 0.09, 0.01, 0.16, 0.02]),
    # k = 5 with a tiny variance in the mix
    ([0.25, 0.24, -0.3, 0.1, 0.0], [1e-10, 0.05, 0.02, 0.03, 0.01]),
    # k = 8 seeded
    (list(rng.normal(0.0, 0.5, 8)), list(rng.uniform(0.005, 0.2, 8))),
    # k = 20 seeded
    (list(rng.normal(0.0, 0.3, 20)), list(rng.uniform(0.002, 0.15, 20))),
    # k = 20 extreme gaps
    (list(np.linspace(-5.0, 5.0, 20)), list(rng.uniform(0.01, 0.05, 20))),
]

for mus, vars_ in MV_CASES:
    mus_a = np.asarray(mus, dtype=float)
    vars_a = np.asarray(vars_, dtype=float)
    k = len(mus)
    m, v, w = P.clark_max_and_weights(mus_a, vars_a)
    lines.append(f"clarkmaxw {k} {fmts(mus)} {fmts(vars_)} {fmt(m)} {fmt(v)} {fmts(w)}")
    d = P.overlap_density(mus_a, vars_a)
    lines.append(f"overlap {k} {fmts(mus)} {fmts(vars_)} {fmts(d)}")


# ---------------------------------------------------------------- shrink
SHRINK_EVALS = {
    2: [0.18, -0.07],
    5: [0.31, -0.12, 0.05, 0.22, -0.4],
    8: list(rng.normal(0.05, 0.3, 8)),
}
V_U = 0.04
ANCHOR_MU = 0.1
ANCHOR_VAR = 0.02

shrink_records = []
for sigma_d in (1e-6, 0.05, 0.3, 5.0):
    for var_s in (0.0, 0.01):
        for is_max in (True, False):
            for k in (2, 5, 8):
                c_k, v_k = P.std_max_moments(k)
                shrink_records.append(
                    (SHRINK_EVALS[k], V_U, var_s, sigma_d, ANCHOR_MU, ANCHOR_VAR, is_max, c_k, v_k))
# v_n <= 1e-18 early-return branch: sigma_d = 0, v_u = 0
shrink_records.append(([0.2, 0.2, 0.2], 0.0, 0.01, 0.0, 0.1, 0.02, True, *P.std_max_moments(3)))

for evals, v_u, var_s, sigma_d, a_mu, a_var, is_max, c_k, v_k in shrink_records:
    k = len(evals)
    mus, v_priv, v_x, kappa = P.shrink_siblings(
        np.asarray(evals, dtype=float), v_u, var_s, sigma_d, a_mu, a_var, is_max,
        d_moments=(c_k, v_k))
    lines.append(
        f"shrink {k} {fmts(evals)} {fmt(v_u)} {fmt(var_s)} {fmt(sigma_d)} "
        f"{fmt(a_mu)} {fmt(a_var)} {1 if is_max else 0} {fmt(c_k)} {fmt(v_k)} "
        f"{fmts(mus)} {fmt(v_priv)} {fmt(v_x)} {fmt(kappa)}")


# ---------------------------------------------------------------- nodepost
NODEPOST_CASES = [
    # (mus, v_privs, bs, var_s, is_max)
    # k = 1
    ([0.2], [0.05], [1.0], 0.01, True),
    # heterogeneous bs incl mixed signs (quadrature path), both node types
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, -0.5, 0.3], 0.01, True),
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, -0.5, 0.3], 0.01, False),
    # homogeneous bs (fast path with b_out = bs[0])
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, 1.0, 1.0], 0.01, True),
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [0.7, 0.7, 0.7], 0.01, False),
    # var_s = 0 (fast path with b_out = 0, heterogeneous bs irrelevant)
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, -0.5, 0.3], 0.0, True),
    ([0.2, -0.1, 0.15], [0.05, 0.2, 0.01], [1.0, -0.5, 0.3], 0.0, False),
    # k = 2 near-tied means, heterogeneous bs
    ([0.5, 0.5000000001], [0.03, 0.07], [0.9, 0.2], 0.02, True),
    # k = 2 extreme mean gap
    ([2.0, -2.0], [0.01, 0.04], [1.0, -1.0], 0.02, True),
    # k = 2 tiny variances
    ([0.1, 0.100001], [1e-10, 1e-10], [0.5, 1.5], 0.005, True),
    # k = 5, mixed-sign bs, both node types
    ([0.3, -0.5, 0.12, 0.11, -0.02], [0.04, 0.09, 0.01, 0.16, 0.02],
     [1.2, -0.3, 0.0, 0.8, -1.0], 0.04, True),
    ([0.3, -0.5, 0.12, 0.11, -0.02], [0.04, 0.09, 0.01, 0.16, 0.02],
     [1.2, -0.3, 0.0, 0.8, -1.0], 0.04, False),
    # k = 8 seeded, heterogeneous bs
    (list(rng.normal(0.0, 0.4, 8)), list(rng.uniform(0.005, 0.15, 8)),
     list(rng.normal(0.5, 0.6, 8)), 0.01, True),
    # k = 20 seeded, heterogeneous bs, min node
    (list(rng.normal(0.0, 0.3, 20)), list(rng.uniform(0.002, 0.1, 20)),
     list(rng.normal(0.0, 1.0, 20)), 0.02, False),
    # k = 20 homogeneous bs (ptp < 1e-12 threshold check: exactly equal)
    (list(rng.normal(0.0, 0.3, 20)), list(rng.uniform(0.002, 0.1, 20)),
     [0.6] * 20, 0.02, True),
]

for mus, v_privs, bs, var_s, is_max in NODEPOST_CASES:
    k = len(mus)
    m, v_priv, b_out, w = P.node_posterior_from_children(
        np.asarray(mus, dtype=float), np.asarray(v_privs, dtype=float),
        np.asarray(bs, dtype=float), var_s, is_max)
    lines.append(
        f"nodepost {k} {fmts(mus)} {fmts(v_privs)} {fmts(bs)} {fmt(var_s)} "
        f"{1 if is_max else 0} {fmt(m)} {fmt(v_priv)} {fmt(b_out)} {fmts(w)}")

# ---------------------------------------------------------------- extmom
# NOTE: rng draws below extend the same seeded stream AFTER all draws above,
# so all earlier records are unchanged on regeneration.
EXTMOM_MEANS = {
    1: [0.12],
    2: [0.25, -0.1],
    5: [0.3, -0.22, 0.05, 0.18, -0.02],
    8: list(rng.normal(0.0, 0.2, 8)),
    20: list(rng.normal(0.0, 0.15, 20)),
    40: list(rng.normal(0.0, 0.25, 40)),
}
for k in (1, 2, 5, 8, 20, 40):
    for sigma_r in (1e-9, 0.05, 0.3):
        for is_max in (True, False):
            e_d, v_d, g = P.extreme_moments_gaussian(
                np.asarray(EXTMOM_MEANS[k], dtype=float), sigma_r, is_max)
            lines.append(
                f"extmom {k} {fmts(EXTMOM_MEANS[k])} {fmt(sigma_r)} "
                f"{1 if is_max else 0} {fmt(e_d)} {fmt(v_d)} {fmt(g)}")


# ---------------------------------------------------------------- stein
STEIN_DMEANS = {
    2: [0.2, -0.15],
    5: [0.3, -0.25, 0.08, -0.02, 0.16],
    8: [0.3, -0.3, 0.12, 0.05, -0.18, 0.22, -0.07, 0.01],
    20: list(rng.normal(0.0, 0.15, 20)),
}
STEIN_EVALS_FULL = {k: list(rng.normal(0.05, 0.25, k)) for k in (2, 5, 8, 20)}
STEIN_A_MU = 0.08
STEIN_A_VAR = 0.015


def emit_stein(k, evals, idx, v_u, var_s, a_mu, a_var, sigma_r, d_moments,
               d_means):
    res = P.shrink_siblings_stein(
        np.asarray(evals, dtype=float), np.asarray(idx, dtype=int), k,
        v_u, var_s, a_mu, a_var, sigma_r, d_moments,
        None if d_means is None else np.asarray(d_means, dtype=float))
    e_d, v_d, g = d_moments
    n = len(evals)
    toks = [f"stein {k} {n}"]
    if n:
        toks.append(fmts(evals))
        toks.append(" ".join(str(int(i)) for i in idx))
    toks.append(f"{fmt(v_u)} {fmt(var_s)} {fmt(a_mu)} {fmt(a_var)} "
                f"{fmt(sigma_r)} {fmt(e_d)} {fmt(v_d)} {fmt(g)}")
    toks.append("1" if d_means is not None else "0")
    if d_means is not None:
        toks.append(fmts(d_means))
    toks.append(f"{fmts(res.mus)} {fmts(res.v_priv)} {fmts(res.b)} "
                f"{fmt(res.V_X)} {fmt(res.kappa_alpha)} {fmt(res.c_ee)} "
                f"{fmt(res.c_uu)} {fmt(res.c_ue)} {fmt(res.v_e)} "
                f"{fmt(res.v_u)}")
    lines.append(" ".join(toks))


# Main battery: n in {0, 1, 2, k-1, k}; v_u/var_s cross; sigma_r sweep;
# d_means None and non-trivial; D_moments from extreme_moments_gaussian on a
# max node (min-node D_moments and hand-set triples covered below).
for k in (2, 5, 8, 20):
    dm = STEIN_DMEANS[k]
    evals_full = STEIN_EVALS_FULL[k]
    for n in sorted(set([0, 1, 2, k - 1, k])):
        idx = sorted(rng.choice(k, size=n, replace=False).tolist())
        evals = [evals_full[j] for j in idx]
        for v_u in (0.0, 0.003):
            for var_s in (0.0, 0.002):
                for sigma_r in (1e-9, 0.03, 0.2):
                    for d_means in (None, dm):
                        base = [0.0] * k if d_means is None else d_means
                        d_moments = P.extreme_moments_gaussian(
                            np.asarray(base, dtype=float), sigma_r, True)
                        emit_stein(k, evals, idx, v_u, var_s, STEIN_A_MU,
                                   STEIN_A_VAR, sigma_r, d_moments, d_means)

# Min-node D_moments (E_D negative-mirrored by extreme_moments_gaussian).
for k in (2, 5, 8, 20):
    dm = STEIN_DMEANS[k]
    n = 2
    idx = [0, k - 1]
    evals = [STEIN_EVALS_FULL[k][j] for j in idx]
    for sigma_r in (1e-9, 0.03, 0.2):
        d_moments = P.extreme_moments_gaussian(
            np.asarray(dm, dtype=float), sigma_r, False)
        emit_stein(k, evals, idx, 0.003, 0.002, STEIN_A_MU, STEIN_A_VAR,
                   sigma_r, d_moments, dm)

# Very negative d_mean in the set (magnitudes beyond the usual 0.3).
DM_NEG = [0.1, -0.9, 0.2, -0.05, 0.3]
for is_max in (True, False):
    d_moments = P.extreme_moments_gaussian(
        np.asarray(DM_NEG, dtype=float), 0.2, is_max)
    emit_stein(5, [0.31, -0.72], [1, 3], 0.003, 0.002, STEIN_A_MU,
               STEIN_A_VAR, 0.2, d_moments, DM_NEG)
    emit_stein(5, [], [], 0.003, 0.002, STEIN_A_MU, STEIN_A_VAR, 0.2,
               d_moments, DM_NEG)

# Hand-set D_moments triples, including g large enough to make c0 NEGATIVE
# (anchor_var small, v_D small, g large), plus the p <= 1e-18 branch with
# n > 0. Fields: (k, evals, idx, v_u, var_s, a_mu, a_var, sigma_r,
# (E_D, v_D, g), d_means).
DM5 = STEIN_DMEANS[5]
DM8 = STEIN_DMEANS[8]
STEIN_HANDSET = [
    # mildly negative c0 (c0 = 1e-4 + 1e-4 - 2*2e-4 = -2e-4), den positive:
    # hits the c_ee > 1e-18 branch with the max(c_uu, 0) clamp active
    (5, [0.31, 0.05], [0, 2], 0.003, 0.002, 0.08, 1e-4, 0.2,
     (0.15, 1e-4, 2e-4), DM5),
    # same but n = 0: c_uu = c0 < 0, falls through to the else branch
    (5, [], [], 0.003, 0.0, 0.08, 1e-4, 0.2, (0.15, 1e-4, 2e-4), None),
    # strongly negative c0 with den < 0 raw: den floored at 1e-12
    (5, [0.31, 0.05], [0, 2], 0.0, 0.0, 0.08, 1e-4, 0.03,
     (0.1, 5e-5, 0.01), DM5),
    # negative c0, full eval set, k = 8
    (8, [0.3, -0.2, 0.1, 0.05, -0.1, 0.2, -0.05, 0.0], list(range(8)),
     0.003, 0.002, 0.08, 5e-4, 0.2, (-0.2, 2e-4, 0.02), DM8),
    # hand-set with large positive E_D/v_D (anchor shift dominates), n = 1
    (5, [0.4], [4], 0.0, 0.002, 0.08, 0.015, 0.03, (0.5, 0.04, 1.8e-4),
     DM5),
    # p <= 1e-18 branch with n > 0 (sigma_r = 0, v_u = 0), with d_means:
    # mean-shift plus exact-eval overwrite
    (5, [0.31, -0.12], [1, 3], 0.0, 0.002, 0.08, 0.015, 0.0,
     (0.12, 0.0, 0.0), DM5),
    # p <= 1e-18, n > 0, no d_means
    (5, [0.31, -0.12], [1, 3], 0.0, 0.0, 0.08, 0.015, 0.0,
     (0.12, 0.0, 0.0), None),
    # p <= 1e-18 via sigma_r = 1e-10 (s2 = 1e-20), full eval set
    (8, [0.3, -0.2, 0.1, 0.05, -0.1, 0.2, -0.05, 0.0], list(range(8)),
     0.0, 0.01, 0.08, 0.02, 1e-10, (0.0, 0.0, 0.0), DM8),
    # p <= 1e-18 with n = 0: mus = m_A + m untouched, all zeros elsewhere
    (5, [], [], 0.0, 0.002, 0.08, 0.015, 0.0, (0.12, 0.0, 0.0), DM5),
]
for (k, evals, idx, v_u, var_s, a_mu, a_var, sigma_r, d_moments,
     d_means) in STEIN_HANDSET:
    emit_stein(k, evals, idx, v_u, var_s, a_mu, a_var, sigma_r, d_moments,
               d_means)

lines.append("end")

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "..", "cpp", "tests", "data", "bayesgolden.txt")
out_path = os.path.normpath(out_path)
with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"Wrote {len(lines)} lines to {out_path}")
